close all;
clear all;


%% Import data from text file.
% Script for importing data from the following text file:
%
%    F:\Optrix_PIX\GFP6_7_191018_0955-201018_0912_23h_Dexmedetomidine.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/08/23 23:24:12



%%%%%% Initialize variables.
filename = 'E:\OptoInh\Calorimetry\Temp\GDVV7-3c_7C_P10_20210412-0941_Dex_postDex_24h.dat'; %GAD34
camera_batch='GAD3_';
mouse_batch='GAD3-';
recorddate='120421';
fnames=char('GAD3','cold');
Dst = 12290; % Inj start
Dst2 = 12546; % Inj end
Dend = 28584; % Antisedan injection
% 
% filename = 'E:\OptoInh\Calorimetry\Temp\GDVV20-4d_7C_P10_20210403_Dex_Calo2119.dat'; %GAD4
% %%%   GDVV20-4d_7C_P10_20210407-0408_2356_Dex
% %%%   GDVV20-4d_7C_P10_20210403_Dex_Calo2119
% %%%   GDVV20-4d_7C_P10_20210407-0408_2356_Dex
% camera_batch='GAD4_';
% mouse_batch='GAD4-';
% recorddate='030421';
% fnames=char('GAD4','cold');
% Dst = 10371; % Inj start
% Dst2 = 10454; % Inj end
% Dend = 25335; % Antisedan injection

% filename = 'E:\OptoInh\Calorimetry\Temp\GOAR7-3d_7B_P10_20210405_Dex_2359.dat'; %GAD5
% camera_batch='GAD5_';
% mouse_batch='GAD5-';
% recorddate='050421';
% fnames=char('GAD5','cold');
% Dst = 11764; % Inj start
% Dst2 = 12166; % Inj end
% Dend = 25653; % Antisedan injection

%  
% filename = 'E:\OptoInh\Calorimetry\Temp\GOAR3-1e_7B_P09_20210410-1918_Dex.dat'; %GAD6
% camera_batch='GAD6_';
% mouse_batch='GAD6-';
% recorddate='100421';
% fnames=char('GAD6','cold');
% Dst = 11808; % Inj start
% Dst2 = 12245; % Inj end
% Dend = 26687; % Antisedan injection


ctemp=22.7;
numdata=2;


path= 'E:\OptoInh\';
pathin = [path,'Dex_dat\']; %mkdir(pathout)
pathout = [path,'temp\';];%mkdir(pathout)
pathout2 = [path,'Calorimetry\'];
pathfig = [path,'Figure_Temp\']; %mkdir(pathfig)
exte='.dat';
delimiter = '\t';
startRow = 8;
% endRow = 81769;

for n=1  %1:size(recorddates)
%     recorddate=recorddates(n,:);   
%     filename = [pathin,camera_batch,recorddate,exte];

%% Format for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
% GFP671910180955201018091223hDexmedetomidine = table(dataArray{1:end-1}, 'VariableNames', {'Time','VarName2','VarName3','ambient','sm','sm1'});

    %% Allocate imported array to column variable names
    Time = dataArray{:, 1}; 
    L1=length(Time)-2; 
%     s1=size(dataArray,2)-2; %exclude the time and the last blank
    Time = Time(1:L1,1);
    
    resampled_ts=[];
    
    %%%% baseline correction %
     temp = dataArray{:, 3}; temp = temp(1:L1,1);
     resampled_temp=temp';
     out=find(resampled_temp>24);resampled_temp(out)=[];
     basetemp=nanmean(resampled_temp);
     corrtemp=ctemp-basetemp;   
            
    for ii=1:numdata%s1%s1
        temp = dataArray{:, ii+1}; temp = temp(1:L1,1);
        out=find(temp>40);temp(out)=NaN;
        
        resampled_temp=temp';
                
        resampled_ts=[resampled_ts, temp];

        corrected_temp=resampled_temp+corrtemp;
        fname=fnames(ii,:); fname(isspace(fname))=[];
        fn=[fname,'_temp_',recorddate,'_Dex']; 
        eval(['save ',pathout,fn,'.mat resampled_temp corrected_temp corrtemp ctemp -mat']);
    end
    
    fn1=[camera_batch,recorddate,'_Dex'];
    eval(['save ',pathout,fn1,'.mat resampled_ts basetemp -mat']);
    
    y1=length(resampled_ts);
    
    %%%%%%%% plot individual TEMP figure

    figure
    plot(resampled_ts)
    hold on
    title([mouse_batch,recorddate])
    
    fn2=[camera_batch,recorddate,'_Dex'];
    saveas(gcf,[pathfig,fn2,'_temp'],'tiff')%'\',mouse,'_',day,'_temp'
%     legend

    %%%%%%%% aligned to Dex/atipamezole injection
    T0=resampled_ts(:,1);
    gap = NaN(50,1);
    nanmat1=NaN*ones(10800,1);
    nanmat2=NaN*ones(10800,1);
    
    if Dst<10800
    T1=nanmat1;
    T1(10800-Dst+1:10800,:)=T0(1:Dst,1);
    else
    T1=T0(Dst-10799:Dst);
    end
    T2=T0(Dst2:Dst2+10799);
    if length(resampled_ts)<Dend+10799
        T3=nanmat1; 
        T3(1:length(resampled_ts)-Dend+1,:)=resampled_ts(Dend:length(resampled_ts),1);
    else
     T3=T0(Dend:Dend+10799);
    end
    
    aPrism_Temp=[T1;T2;T3];
    fn5=[camera_batch,'DexTempAligned'];
    eval(['save ',pathout2,fn5,'.mat aPrism_Temp -mat']);
    
%     test2 = reshape(aPrism_Temp,[],3600);


    %% Clear temporary variables
    clearvars filename fileID dataArray ans;
end
clearvars delimiter startRow formatSpec ;